# action.yml
name: 'Update Cover'
description: 'Runs Dynacover to update Twitter banner'
icon: image
color: purple
inputs:
  template:
    description: 'Template to Use'
    required: false
    default: 'cover_basic.json'
outputs:
  response:
    description: 'Output'
runs:
  using: 'docker'
  image: 'Dockerfile'
