# action.yml
name: 'Dynacover'
description: 'Generate dynamic Twitter header images with latest followers'
author: 'Erika Heidi'
branding:
  icon: 'image'
  color: 'purple'
inputs:
  template:
    description: 'Cover template to Use'
    required: false
    default: 'cover_basic.json'
outputs:
  response:
    description: 'Output'
runs:
  using: 'docker'
  image: 'Dockerfile'
